default:
	@echo Only available target is for "make clean"

clean:
	rm -rf example-mpi-cpp example-serial-cpp
	rm -rf example-mpi-c example-serial-c
	rm -rf example-mpi-f example-serial-f
	rm -rf example-*.bp
